### PR TITLE
Update for Qiskit 1.0

### PR DESCRIPTION
**Pull request by frankharkins**
Minor tweaks to make this project work with Qiskit 1.0

* `execute` -> `transpile` & `backend.run`
* `qiskit.tools.visualization` -> `qiskit.visualization`
* `qiskit.extensions.UnitaryGate` -> `qiskit.circuit.library.UnitaryGate`

### CODE REVIEW

**Comment by MarquessV** [comment]
@frankharkins Thank you for doing this! I approved CI to run on this PR. Looks like tests are failing due to  `ImportError: cannot import name 'UnitaryGate' from 'qiskit.circuit.library'`. 

Also, are these changes intended to be compatible with the Qiskit version this library currently supports (>=0.38)? Just want to check if we should update the constraint in `pyproject.toml`.

**Comment by frankharkins** [comment]
Hi, sorry I missed this. I've just pushed a commit that should add backwards compatibility for earlier Qiskit versions, so hopefully you won't need to update your dependencies.
